# Generated by Django 4.2.16 on 2025-09-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'workshop', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'workshop')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'workshop')},
        ),
    ]
